version: "3.8"

services:
  webrtc-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    environment:
      - CAMERA_ID=0
    volumes:
      - .:/app
    restart: unless-stopped
    devices:
      - "/dev/video0:/dev/video0"

