
services:
  webrtc-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    volumes:
      - .:/app
    restart: unless-stopped
    privileged: true
    network_mode: host
    devices:
      - "/dev/video1:/dev/video0"

